
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: eureka-consumer
  
feign:
  hystrix:
    enabled: true
    
ribbon:
  eureka:
    enabled: true